
package com.tap.ws.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://com/customer/webservices/customerSvc")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerService {


    /**
     * 
     * @param addCustomerRequest
     * @return
     *     returns com.tap.ws.stubs.AddCustomerResponse
     */
    @WebMethod
    @WebResult(name = "addCustomerResponse", targetNamespace = "http://com/customer/webservices/customerSvc", partName = "addCustomerResponse")
    public AddCustomerResponse addCustomer(
        @WebParam(name = "addCustomerRequest", targetNamespace = "http://com/customer/webservices/customerSvc", partName = "addCustomerRequest")
        AddCustomerRequest addCustomerRequest);

    /**
     * 
     * @param updateCustomerRequest
     * @return
     *     returns com.tap.ws.stubs.UpdateCustomerResponse
     */
    @WebMethod
    @WebResult(name = "updateCustomerResponse", targetNamespace = "http://com/customer/webservices/customerSvc", partName = "updateCustomerResponse")
    public UpdateCustomerResponse updateCustomer(
        @WebParam(name = "updateCustomerRequest", targetNamespace = "http://com/customer/webservices/customerSvc", partName = "updateCustomerRequest")
        UpdateCustomerRequest updateCustomerRequest);

    /**
     * 
     * @param getAllCustomersRequest
     * @return
     *     returns com.tap.ws.stubs.GetAllCustomersResponse
     */
    @WebMethod
    @WebResult(name = "getAllCustomersResponse", targetNamespace = "http://com/customer/webservices/customerSvc", partName = "getAllCustomersResponse")
    public GetAllCustomersResponse getAllCustomers(
        @WebParam(name = "getAllCustomersRequest", targetNamespace = "http://com/customer/webservices/customerSvc", partName = "getAllCustomersRequest")
        GetAllCustomersRequest getAllCustomersRequest);

    /**
     * 
     * @param deleteCustomerRequest
     * @return
     *     returns com.tap.ws.stubs.DeleteCustomerResponse
     */
    @WebMethod
    @WebResult(name = "deleteCustomerResponse", targetNamespace = "http://com/customer/webservices/customerSvc", partName = "deleteCustomerResponse")
    public DeleteCustomerResponse deleteCustomer(
        @WebParam(name = "deleteCustomerRequest", targetNamespace = "http://com/customer/webservices/customerSvc", partName = "deleteCustomerRequest")
        DeleteCustomerRequest deleteCustomerRequest);

    /**
     * 
     * @param getCustomerRequest
     * @return
     *     returns com.tap.ws.stubs.GetCustomerResponse
     */
    @WebMethod
    @WebResult(name = "getCustomerResponse", targetNamespace = "http://com/customer/webservices/customerSvc", partName = "getCustomerResponse")
    public GetCustomerResponse getCustomer(
        @WebParam(name = "getCustomerRequest", targetNamespace = "http://com/customer/webservices/customerSvc", partName = "getCustomerRequest")
        GetCustomerRequest getCustomerRequest);

}
