
package com.tap.ws.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CustomerServices", targetNamespace = "http://com/customer/webservices/customerSvc", wsdlLocation = "file:/C:/Workspace/GitHub/Spring/trackApp/src/main/resources/CustomerWS.wsdl")
public class CustomerServices
    extends Service
{

    private final static URL CUSTOMERSERVICES_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERSERVICES_EXCEPTION;
    private final static QName CUSTOMERSERVICES_QNAME = new QName("http://com/customer/webservices/customerSvc", "CustomerServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Workspace/GitHub/Spring/trackApp/src/main/resources/CustomerWS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERSERVICES_WSDL_LOCATION = url;
        CUSTOMERSERVICES_EXCEPTION = e;
    }

    public CustomerServices() {
        super(__getWsdlLocation(), CUSTOMERSERVICES_QNAME);
    }

    public CustomerServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERSERVICES_QNAME, features);
    }

    public CustomerServices(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERSERVICES_QNAME);
    }

    public CustomerServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERSERVICES_QNAME, features);
    }

    public CustomerServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomerService
     */
    @WebEndpoint(name = "CustomerServiceSoap11")
    public CustomerService getCustomerServiceSoap11() {
        return super.getPort(new QName("http://com/customer/webservices/customerSvc", "CustomerServiceSoap11"), CustomerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerService
     */
    @WebEndpoint(name = "CustomerServiceSoap11")
    public CustomerService getCustomerServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://com/customer/webservices/customerSvc", "CustomerServiceSoap11"), CustomerService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERSERVICES_EXCEPTION!= null) {
            throw CUSTOMERSERVICES_EXCEPTION;
        }
        return CUSTOMERSERVICES_WSDL_LOCATION;
    }

}
