
package com.blog.samples.webservices.personservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonService", targetNamespace = "http://com/blog/samples/webservices/personservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonService {


    /**
     * 
     * @param addPersonRequest
     * @return
     *     returns com.blog.samples.webservices.personservice.AddPersonResponse
     */
    @WebMethod
    @WebResult(name = "addPersonResponse", targetNamespace = "http://com/blog/samples/webservices/personservice", partName = "addPersonResponse")
    public AddPersonResponse addPerson(
        @WebParam(name = "addPersonRequest", targetNamespace = "http://com/blog/samples/webservices/personservice", partName = "addPersonRequest")
        AddPersonRequest addPersonRequest);

    /**
     * 
     * @param updatePersonRequest
     * @return
     *     returns com.blog.samples.webservices.personservice.UpdatePersonResponse
     */
    @WebMethod
    @WebResult(name = "updatePersonResponse", targetNamespace = "http://com/blog/samples/webservices/personservice", partName = "updatePersonResponse")
    public UpdatePersonResponse updatePerson(
        @WebParam(name = "updatePersonRequest", targetNamespace = "http://com/blog/samples/webservices/personservice", partName = "updatePersonRequest")
        UpdatePersonRequest updatePersonRequest);

    /**
     * 
     * @param getAllPersonsRequest
     * @return
     *     returns com.blog.samples.webservices.personservice.GetAllPersonsResponse
     */
    @WebMethod
    @WebResult(name = "getAllPersonsResponse", targetNamespace = "http://com/blog/samples/webservices/personservice", partName = "getAllPersonsResponse")
    public GetAllPersonsResponse getAllPersons(
        @WebParam(name = "getAllPersonsRequest", targetNamespace = "http://com/blog/samples/webservices/personservice", partName = "getAllPersonsRequest")
        GetAllPersonsRequest getAllPersonsRequest);

    /**
     * 
     * @param deletePersonRequest
     * @return
     *     returns com.blog.samples.webservices.personservice.DeletePersonResponse
     */
    @WebMethod
    @WebResult(name = "deletePersonResponse", targetNamespace = "http://com/blog/samples/webservices/personservice", partName = "deletePersonResponse")
    public DeletePersonResponse deletePerson(
        @WebParam(name = "deletePersonRequest", targetNamespace = "http://com/blog/samples/webservices/personservice", partName = "deletePersonRequest")
        DeletePersonRequest deletePersonRequest);

    /**
     * 
     * @param getPersonRequest
     * @return
     *     returns com.blog.samples.webservices.personservice.GetPersonResponse
     */
    @WebMethod
    @WebResult(name = "getPersonResponse", targetNamespace = "http://com/blog/samples/webservices/personservice", partName = "getPersonResponse")
    public GetPersonResponse getPerson(
        @WebParam(name = "getPersonRequest", targetNamespace = "http://com/blog/samples/webservices/personservice", partName = "getPersonRequest")
        GetPersonRequest getPersonRequest);

}
